In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
random_state=660601
listings = 'listings.csv'

In [4]:
df_listings = pd.read_csv(listings, index_col='id', engine='python', sep =',', encoding="utf-8")
print('Total de registros carregados:',len(df_listings))
df_listings.head()

Total de registros carregados: 33715

,listing_url,scrape_id,last_scraped,name,summary,space,description,experiences_offered,neighborhood_overview,notes,...,instant_bookable,is_business_travel_ready,cancellation_policy,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
id,,,,,,,,,,,,,,,,,,,,,
17878,https://www.airbnb.com/rooms/17878,20191122092441,2019-11-22,Very Nice 2Br - Copacabana - WiFi,Pls note that special rates apply for Carnival...,- large balcony which looks out on pedestrian ...,Pls note that special rates apply for Carnival...,none,This is the best spot in Rio. Everything happe...,NaN,...,t,f,strict_14_with_grace_period,f,f,1,1,0,0,2.13
25026,https://www.airbnb.com/rooms/25026,20191122092441,2019-11-22,Beautiful Modern Decorated Studio in Copa,"Our apartment is a little gem, everyone loves ...",This newly renovated studio (last renovations ...,"Our apartment is a little gem, everyone loves ...",none,Copacabana is a lively neighborhood and the ap...,"For any stay superior to 15 days, an additiona...",...,f,f,strict_14_with_grace_period,t,t,3,3,0,0,2.04
31560,https://www.airbnb.com/rooms/31560,20191122092441,2019-11-22,NICE & COZY 1BDR - IPANEMA BEACH,This nice and clean 1 bedroom apartment is loc...,This nice and clean 1 bedroom apartment is loc...,This nice and clean 1 bedroom apartment is loc...,none,Die Nachbarschaft von Ipanema ist super lebend...,NaN,...,t,f,strict_14_with_grace_period,f,f,1,1,0,0,2.38
35636,https://www.airbnb.com/rooms/35636,20191122092441,2019-11-22,Cosy flat close to Ipanema beach,This cosy apartment is just a few steps away ...,"The location is extremely convenient, safe and...",This cosy apartment is just a few steps away ...,none,The apartment street is very quiet and safe ....,Please include the following information with ...,...,f,f,strict_14_with_grace_period,t,t,1,1,0,0,2.28
35764,https://www.airbnb.com/rooms/35764,20191122092441,2019-11-22,COPACABANA SEA BREEZE - RIO - 20 X Superhost,Our newly renovated studio is located in the b...,"FEEL LIKE YOUR HOME LIVING AS ""CARIOCA"" LOCAL ...",Our newly renovated studio is located in the b...,none,Our guests will experience living with a local...,Our guests no need to worry about breakfast a...,...,f,f,strict_14_with_grace_period,f,t,1,1,0,0,2.84

In [11]:
df_listings_filtered = df_listings[['host_name', 'host_response_time', 'host_response_rate', 'host_is_superhost', 'host_identity_verified', 'neighbourhood', 'zipcode', 'latitude', 'longitude', 'property_type', 'room_type', 'accommodates', 'bathrooms', 'bedrooms', 'beds', 'bed_type', 'amenities', 'price', 'security_deposit', 'cleaning_fee', 'guests_included', 'extra_people', 'minimum_nights', 'maximum_nights', 'number_of_reviews', 'review_scores_rating', 'review_scores_accuracy', 'review_scores_cleanliness', 'review_scores_checkin', 'review_scores_communication', 'review_scores_location', 'review_scores_value', 'instant_bookable', 'cancellation_policy', 'calculated_host_listings_count', 'reviews_per_month']]
df_listings_filtered.head()

,host_name,host_response_time,host_response_rate,host_is_superhost,host_identity_verified,neighbourhood,zipcode,latitude,longitude,property_type,...,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable,cancellation_policy,calculated_host_listings_count,reviews_per_month
id,,,,,,,,,,,,,,,,,,,,,
17878,Matthias,within an hour,100%,t,t,Copacabana,22020-050,-22.96592,-43.17896,Condominium,...,9.0,10.0,10.0,10.0,10.0,9.0,t,strict_14_with_grace_period,1,2.13
25026,Viviane,within a day,91%,f,t,Copacabana,22060-020,-22.97712,-43.19045,Apartment,...,9.0,10.0,9.0,10.0,10.0,9.0,f,strict_14_with_grace_period,3,2.04
31560,Renata,within an hour,100%,t,t,Ipanema,22410-003,-22.98302,-43.21427,Apartment,...,10.0,10.0,10.0,10.0,10.0,10.0,t,strict_14_with_grace_period,1,2.38
35636,Patricia,within an hour,100%,t,t,Ipanema,22081-020,-22.98816,-43.19359,Apartment,...,10.0,9.0,10.0,10.0,10.0,9.0,f,strict_14_with_grace_period,1,2.28
35764,Patricia Miranda & Paulo,within an hour,100%,t,t,Copacabana,21031-300,-22.98127,-43.19046,Loft,...,10.0,10.0,10.0,10.0,10.0,10.0,f,strict_14_with_grace_period,1,2.84

In [21]:
df_listings_filtered.describe()

,latitude,longitude,accommodates,bathrooms,bedrooms,beds,guests_included,minimum_nights,maximum_nights,number_of_reviews,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,calculated_host_listings_count,reviews_per_month
count,33715.000000,33715.000000,33715.000000,33661.000000,33673.000000,33667.000000,33715.000000,33715.000000,3.371500e+04,33715.000000,18293.000000,18275.00000,18280.000000,18274.000000,18280.000000,18277.000000,18278.000000,33715.000000,19149.000000
mean,-22.965208,-43.254228,4.199941,1.694765,1.646126,2.574242,1.718434,4.789826,9.571741e+02,9.374344,94.777565,9.65658,9.431565,9.802561,9.775656,9.748044,9.332093,5.996292,0.707232
std,0.035244,0.097488,2.625252,1.508228,1.075649,2.121490,1.585645,22.640328,5.473614e+04,24.815311,9.141386,0.88463,1.079031,0.713238,0.744620,0.734016,1.016906,20.303420,0.927453
min,-23.073400,-43.737090,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000e+00,0.000000,20.000000,2.00000,2.000000,2.000000,2.000000,2.000000,2.000000,1.000000,0.010000
25%,-22.984710,-43.323360,2.000000,1.000000,1.000000,1.000000,1.000000,1.000000,3.000000e+01,0.000000,93.000000,10.00000,9.000000,10.000000,10.000000,10.000000,9.000000,1.000000,0.110000
50%,-22.970850,-43.200220,4.000000,1.000000,1.000000,2.000000,1.000000,2.000000,1.125000e+03,1.000000,98.000000,10.00000,10.000000,10.000000,10.000000,10.000000,10.000000,1.000000,0.340000
75%,-22.946725,-43.187085,6.000000,2.000000,2.000000,3.000000,2.000000,4.000000,1.125000e+03,6.000000,100.000000,10.00000,10.000000,10.000000,10.000000,10.000000,10.000000,3.000000,0.980000
max,-22.750380,-43.104060,160.000000,200.000000,20.000000,69.000000,25.000000,1123.000000,1.000000e+07,372.000000,100.000000,10.00000,10.000000,10.000000,10.000000,10.000000,10.000000,205.000000,10.080000

In [22]:
df_listings_filtered_sampled = df_listings_filtered.sample(10000)

In [24]:
df_listings_filtered_sampled.describe()

,latitude,longitude,accommodates,bathrooms,bedrooms,beds,guests_included,minimum_nights,maximum_nights,number_of_reviews,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,calculated_host_listings_count,reviews_per_month
count,10000.000000,10000.000000,10000.000000,9985.000000,9990.000000,9985.000000,10000.00000,10000.000000,10000.000000,10000.000000,5382.000000,5379.000000,5379.000000,5377.000000,5381.000000,5380.000000,5380.000000,10000.000000,5612.000000
mean,-22.965435,-43.253113,4.256400,1.698948,1.672673,2.594692,1.70230,4.552200,631.215700,9.350200,94.759569,9.651236,9.427961,9.797099,9.770675,9.765613,9.322119,6.233000,0.706058
std,0.034741,0.096817,2.964952,1.061936,1.084739,2.190742,1.54852,20.945681,711.363634,25.064265,8.841549,0.868193,1.061763,0.686774,0.727195,0.662579,0.993824,21.402615,0.919527
min,-23.072970,-43.689050,1.000000,0.000000,0.000000,0.000000,1.00000,1.000000,1.000000,0.000000,20.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,1.000000,0.010000
25%,-22.984680,-43.320702,2.000000,1.000000,1.000000,1.000000,1.00000,1.000000,30.000000,0.000000,93.000000,10.000000,9.000000,10.000000,10.000000,10.000000,9.000000,1.000000,0.110000
50%,-22.970845,-43.200220,4.000000,1.000000,1.000000,2.000000,1.00000,2.000000,1125.000000,1.000000,98.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,1.000000,0.340000
75%,-22.948225,-43.187040,6.000000,2.000000,2.000000,3.000000,2.00000,4.000000,1125.000000,6.000000,100.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,3.000000,0.970000
max,-22.751960,-43.104620,160.000000,17.000000,13.000000,69.000000,25.00000,1095.000000,47036.000000,372.000000,100.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,205.000000,8.140000