In [39]:
import pandas as pd
import numpy as np

In [40]:
df_listings = pd.read_csv('listings.csv', index_col='id', engine='python', sep =',', encoding="utf-8")
print('Total de registros carregados:',len(df_listings))
df_listings.head()

Total de registros carregados: 33715

,listing_url,scrape_id,last_scraped,name,summary,space,description,experiences_offered,neighborhood_overview,notes,...,instant_bookable,is_business_travel_ready,cancellation_policy,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
id,,,,,,,,,,,,,,,,,,,,,
17878,https://www.airbnb.com/rooms/17878,20191122092441,2019-11-22,Very Nice 2Br - Copacabana - WiFi,Pls note that special rates apply for Carnival...,- large balcony which looks out on pedestrian ...,Pls note that special rates apply for Carnival...,none,This is the best spot in Rio. Everything happe...,NaN,...,t,f,strict_14_with_grace_period,f,f,1,1,0,0,2.13
25026,https://www.airbnb.com/rooms/25026,20191122092441,2019-11-22,Beautiful Modern Decorated Studio in Copa,"Our apartment is a little gem, everyone loves ...",This newly renovated studio (last renovations ...,"Our apartment is a little gem, everyone loves ...",none,Copacabana is a lively neighborhood and the ap...,"For any stay superior to 15 days, an additiona...",...,f,f,strict_14_with_grace_period,t,t,3,3,0,0,2.04
31560,https://www.airbnb.com/rooms/31560,20191122092441,2019-11-22,NICE & COZY 1BDR - IPANEMA BEACH,This nice and clean 1 bedroom apartment is loc...,This nice and clean 1 bedroom apartment is loc...,This nice and clean 1 bedroom apartment is loc...,none,Die Nachbarschaft von Ipanema ist super lebend...,NaN,...,t,f,strict_14_with_grace_period,f,f,1,1,0,0,2.38
35636,https://www.airbnb.com/rooms/35636,20191122092441,2019-11-22,Cosy flat close to Ipanema beach,This cosy apartment is just a few steps away ...,"The location is extremely convenient, safe and...",This cosy apartment is just a few steps away ...,none,The apartment street is very quiet and safe ....,Please include the following information with ...,...,f,f,strict_14_with_grace_period,t,t,1,1,0,0,2.28
35764,https://www.airbnb.com/rooms/35764,20191122092441,2019-11-22,COPACABANA SEA BREEZE - RIO - 20 X Superhost,Our newly renovated studio is located in the b...,"FEEL LIKE YOUR HOME LIVING AS ""CARIOCA"" LOCAL ...",Our newly renovated studio is located in the b...,none,Our guests will experience living with a local...,Our guests no need to worry about breakfast a...,...,f,f,strict_14_with_grace_period,f,t,1,1,0,0,2.84

In [41]:
df_listings_filtered = df_listings[['host_name', 'host_response_time', 'host_response_rate', 'host_is_superhost', 'host_identity_verified', 'neighbourhood', 'zipcode', 'latitude', 'longitude', 'property_type', 'room_type', 'accommodates', 'bathrooms', 'bedrooms', 'beds', 'bed_type', 'amenities', 'price', 'security_deposit', 'cleaning_fee', 'guests_included', 'extra_people', 'minimum_nights', 'maximum_nights', 'number_of_reviews', 'review_scores_rating', 'review_scores_accuracy', 'review_scores_cleanliness', 'review_scores_checkin', 'review_scores_communication', 'review_scores_location', 'review_scores_value', 'instant_bookable', 'cancellation_policy', 'calculated_host_listings_count', 'reviews_per_month']]
df_listings_filtered.head()

,host_name,host_response_time,host_response_rate,host_is_superhost,host_identity_verified,neighbourhood,zipcode,latitude,longitude,property_type,...,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable,cancellation_policy,calculated_host_listings_count,reviews_per_month
id,,,,,,,,,,,,,,,,,,,,,
17878,Matthias,within an hour,100%,t,t,Copacabana,22020-050,-22.96592,-43.17896,Condominium,...,9.0,10.0,10.0,10.0,10.0,9.0,t,strict_14_with_grace_period,1,2.13
25026,Viviane,within a day,91%,f,t,Copacabana,22060-020,-22.97712,-43.19045,Apartment,...,9.0,10.0,9.0,10.0,10.0,9.0,f,strict_14_with_grace_period,3,2.04
31560,Renata,within an hour,100%,t,t,Ipanema,22410-003,-22.98302,-43.21427,Apartment,...,10.0,10.0,10.0,10.0,10.0,10.0,t,strict_14_with_grace_period,1,2.38
35636,Patricia,within an hour,100%,t,t,Ipanema,22081-020,-22.98816,-43.19359,Apartment,...,10.0,9.0,10.0,10.0,10.0,9.0,f,strict_14_with_grace_period,1,2.28
35764,Patricia Miranda & Paulo,within an hour,100%,t,t,Copacabana,21031-300,-22.98127,-43.19046,Loft,...,10.0,10.0,10.0,10.0,10.0,10.0,f,strict_14_with_grace_period,1,2.84

In [42]:
df_listings_filtered.describe()

,latitude,longitude,accommodates,bathrooms,bedrooms,beds,guests_included,minimum_nights,maximum_nights,number_of_reviews,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,calculated_host_listings_count,reviews_per_month
count,33715.000000,33715.000000,33715.000000,33661.000000,33673.000000,33667.000000,33715.000000,33715.000000,3.371500e+04,33715.000000,18293.000000,18275.00000,18280.000000,18274.000000,18280.000000,18277.000000,18278.000000,33715.000000,19149.000000
mean,-22.965208,-43.254228,4.199941,1.694765,1.646126,2.574242,1.718434,4.789826,9.571741e+02,9.374344,94.777565,9.65658,9.431565,9.802561,9.775656,9.748044,9.332093,5.996292,0.707232
std,0.035244,0.097488,2.625252,1.508228,1.075649,2.121490,1.585645,22.640328,5.473614e+04,24.815311,9.141386,0.88463,1.079031,0.713238,0.744620,0.734016,1.016906,20.303420,0.927453
min,-23.073400,-43.737090,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000e+00,0.000000,20.000000,2.00000,2.000000,2.000000,2.000000,2.000000,2.000000,1.000000,0.010000
25%,-22.984710,-43.323360,2.000000,1.000000,1.000000,1.000000,1.000000,1.000000,3.000000e+01,0.000000,93.000000,10.00000,9.000000,10.000000,10.000000,10.000000,9.000000,1.000000,0.110000
50%,-22.970850,-43.200220,4.000000,1.000000,1.000000,2.000000,1.000000,2.000000,1.125000e+03,1.000000,98.000000,10.00000,10.000000,10.000000,10.000000,10.000000,10.000000,1.000000,0.340000
75%,-22.946725,-43.187085,6.000000,2.000000,2.000000,3.000000,2.000000,4.000000,1.125000e+03,6.000000,100.000000,10.00000,10.000000,10.000000,10.000000,10.000000,10.000000,3.000000,0.980000
max,-22.750380,-43.104060,160.000000,200.000000,20.000000,69.000000,25.000000,1123.000000,1.000000e+07,372.000000,100.000000,10.00000,10.000000,10.000000,10.000000,10.000000,10.000000,205.000000,10.080000

In [43]:
df_listings_filtered_sampled = df_listings_filtered.sample(10000)

In [44]:
df_listings_filtered_sampled.describe()

,latitude,longitude,accommodates,bathrooms,bedrooms,beds,guests_included,minimum_nights,maximum_nights,number_of_reviews,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,calculated_host_listings_count,reviews_per_month
count,10000.000000,10000.000000,10000.000000,9985.000000,9989.000000,9988.000000,10000.00000,10000.000000,1.000000e+04,10000.000000,5431.000000,5426.000000,5428.000000,5426.000000,5428.000000,5425.000000,5426.000000,10000.000000,5671.000000
mean,-22.965847,-43.254617,4.225700,1.694692,1.662128,2.596516,1.71790,4.885400,1.619957e+03,9.446600,94.703922,9.658865,9.430914,9.811832,9.779477,9.742488,9.329709,5.835200,0.696036
std,0.034664,0.096897,2.521665,1.045802,1.084934,2.136570,1.57828,25.473311,9.999527e+04,25.015802,9.180148,0.877109,1.082474,0.714418,0.756159,0.740881,1.023156,20.194688,0.913409
min,-23.073400,-43.737090,1.000000,0.000000,0.000000,0.000000,1.00000,1.000000,1.000000e+00,0.000000,20.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,1.000000,0.010000
25%,-22.984800,-43.326068,2.000000,1.000000,1.000000,1.000000,1.00000,1.000000,3.000000e+01,0.000000,93.000000,10.000000,9.000000,10.000000,10.000000,10.000000,9.000000,1.000000,0.105000
50%,-22.971290,-43.200555,4.000000,1.000000,1.000000,2.000000,1.00000,2.000000,1.125000e+03,1.000000,98.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,1.000000,0.330000
75%,-22.949653,-43.187200,6.000000,2.000000,2.000000,3.000000,2.00000,4.000000,1.125000e+03,6.000000,100.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,2.000000,0.970000
max,-22.750500,-43.107830,25.000000,15.000000,17.000000,50.000000,22.00000,1000.000000,1.000000e+07,366.000000,100.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,205.000000,8.410000

In [45]:
dados_ausentes_media = ['review_scores_rating', 'review_scores_accuracy', 'review_scores_cleanliness', 'review_scores_checkin', 'review_scores_communication', 'review_scores_location', 'review_scores_value', 'reviews_per_month']
dados_ausentes_minimo = ['bathrooms', 'bedrooms', 'beds']
df_listings_filtered_sampled.fillna(df_listings_filtered_sampled[dados_ausentes_media].mean(), inplace=True)
df_listings_filtered_sampled.fillna(df_listings_filtered_sampled[dados_ausentes_minimo].min(), inplace=True)
df_listings_filtered_sampled.fillna(value='nd', inplace=True)
df_listings_filtered_sampled.describe()

,latitude,longitude,accommodates,bathrooms,bedrooms,beds,guests_included,minimum_nights,maximum_nights,number_of_reviews,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,calculated_host_listings_count,reviews_per_month
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,-22.965847,-43.254617,4.225700,1.692150,1.660300,2.593400,1.71790,4.885400,1.619957e+03,9.446600,94.703922,9.658865,9.430914,9.811832,9.779477,9.742488,9.329709,5.835200,0.696036
std,0.034664,0.096897,2.521665,1.047074,1.085736,2.137179,1.57828,25.473311,9.999527e+04,25.015802,6.765055,0.646063,0.797479,0.526228,0.557077,0.545670,0.753639,20.194688,0.687826
min,-23.073400,-43.737090,1.000000,0.000000,0.000000,0.000000,1.00000,1.000000,1.000000e+00,0.000000,20.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,1.000000,0.010000
25%,-22.984800,-43.326068,2.000000,1.000000,1.000000,1.000000,1.00000,1.000000,3.000000e+01,0.000000,94.703922,9.658865,9.430914,9.811832,9.779477,9.742488,9.329709,1.000000,0.240000
50%,-22.971290,-43.200555,4.000000,1.000000,1.000000,2.000000,1.00000,2.000000,1.125000e+03,1.000000,94.703922,9.658865,9.430914,9.811832,9.779477,9.742488,9.329709,1.000000,0.696036
75%,-22.949653,-43.187200,6.000000,2.000000,2.000000,3.000000,2.00000,4.000000,1.125000e+03,6.000000,99.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,2.000000,0.696036
max,-22.750500,-43.107830,25.000000,15.000000,17.000000,50.000000,22.00000,1000.000000,1.000000e+07,366.000000,100.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,205.000000,8.410000

In [46]:
df_listings_filtered_sampled['amenities']

id
14089799    {Wifi,"Smoking allowed",Essentials,"Laptop fri...
2301394     {TV,"Cable TV",Internet,Wifi,"Air conditioning...
22117621    {TV,"Cable TV",Wifi,"Air conditioning",Pool,Ki...
22406380    {TV,"Cable TV",Wifi,"Paid parking off premises...
15954965    {TV,Internet,Wifi,"Air conditioning",Kitchen,"...
                                  ...
38624274    {TV,Wifi,"Air conditioning",Kitchen,"Smoking a...
18421240    {TV,Wifi,"Air conditioning",Kitchen,Elevator,H...
27546853    {TV,Wifi,"Air conditioning",Kitchen,"Safety ca...
13858440    {TV,"Cable TV","Air conditioning",Kitchen,Elev...
13848383    {TV,Wifi,Pool,Kitchen,"Free parking on premise...
Name: amenities, Length: 10000, dtype: object

In [47]:
amenities_list = df_listings_filtered_sampled['amenities'].str.strip('}{').str.replace(' ', '_').str.replace('"', '').str.split(',')

In [48]:
amenities_list

id
14089799    [Wifi, Smoking_allowed, Essentials, Laptop_fri...
2301394     [TV, Cable_TV, Internet, Wifi, Air_conditionin...
22117621    [TV, Cable_TV, Wifi, Air_conditioning, Pool, K...
22406380    [TV, Cable_TV, Wifi, Paid_parking_off_premises...
15954965    [TV, Internet, Wifi, Air_conditioning, Kitchen...
                                  ...
38624274    [TV, Wifi, Air_conditioning, Kitchen, Smoking_...
18421240    [TV, Wifi, Air_conditioning, Kitchen, Elevator...
27546853    [TV, Wifi, Air_conditioning, Kitchen, Safety_c...
13858440    [TV, Cable_TV, Air_conditioning, Kitchen, Elev...
13848383    [TV, Wifi, Pool, Kitchen, Free_parking_on_prem...
Name: amenities, Length: 10000, dtype: object

In [49]:
from sklearn.preprocessing import MultiLabelBinarizer
mlb = MultiLabelBinarizer()
amenities_matriz = mlb.fit_transform(amenities_list)
amenities_matriz

array([[0, 0, 0, ..., 0, 1, 1],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 1]])

In [50]:
amenities_colunas = mlb.classes_
amenities_colunas

array(['', '24-hour_check-in', 'Accessible-height_bed',
       'Accessible-height_toilet', 'Air_conditioning', 'BBQ_grill',
       'Baby_bath', 'Baby_monitor', 'Babysitter_recommendations',
       'Balcony', 'Bath_towel', 'Bathroom_essentials', 'Bathtub',
       'Bathtub_with_bath_chair', 'Beach_essentials', 'Beachfront',
       'Bed_linens', 'Bedroom_comforts', 'Body_soap', 'Breakfast',
       'Breakfast_table', 'Building_staff', 'Buzzer/wireless_intercom',
       'Cable_TV', 'Carbon_monoxide_detector', 'Cat(s)', 'Ceiling_fan',
       'Changing_table', 'Children’s_books_and_toys',
       'Children’s_dinnerware', 'Cleaning_before_checkout',
       'Coffee_maker', 'Cooking_basics', 'Crib', 'DVD_player', 'Day_bed',
       'Disabled_parking_spot', 'Dishes_and_silverware', 'Dishwasher',
       'Dog(s)', 'Doorman', 'Dryer', 'EV_charger',
       'Electric_profiling_bed', 'Elevator', 'En_suite_bathroom',
       'Espresso_machine', 'Essentials', 'Ethernet_connection',
       'Extra_pillows_and_blankets', 'Extra_space_around_bed',
       'Family/kid_friendly', 'Fire_extinguisher', 'Fireplace_guards',
       'Firm_mattress', 'First_aid_kit', 'Fixed_grab_bars_for_shower',
       'Fixed_grab_bars_for_toilet', 'Flat_path_to_guest_entrance',
       'Free_parking_on_premises', 'Free_street_parking', 'Full_kitchen',
       'Game_console', 'Garden_or_backyard', 'Gas_oven',
       'Ground_floor_access', 'Gym', 'Hair_dryer', 'Handheld_shower_head',
       'Hangers', 'Heating', 'High_chair', 'Host_greets_you', 'Hot_tub',
       'Hot_water', 'Hot_water_kettle', 'Indoor_fireplace', 'Internet',
       'Iron', 'Keypad', 'Kitchen', 'Kitchenette', 'Lake_access',
       'Laptop_friendly_workspace', 'Lock_on_bedroom_door', 'Lockbox',
       'Long_term_stays_allowed', 'Luggage_dropoff_allowed', 'Microwave',
       'Mini_fridge', 'Mobile_hoist', 'Mountain_view', 'Murphy_bed',
       'Netflix', 'No_stairs_or_steps_to_enter', 'Other', 'Other_pet(s)',
       'Outdoor_seating', 'Outlet_covers', 'Oven',
       'Pack_’n_Play/travel_crib', 'Paid_parking_off_premises',
       'Paid_parking_on_premises', 'Patio_or_balcony', 'Pets_allowed',
       'Pets_live_on_this_property', 'Pillow-top_mattress', 'Pocket_wifi',
       'Pool', 'Pool_with_pool_hoist', 'Private_entrance',
       'Private_living_room', 'Private_pool', 'Rain_shower',
       'Refrigerator', 'Room-darkening_shades', 'Safety_card',
       'Self_check-in', 'Shampoo', 'Shower_chair', 'Single_level_home',
       'Ski-in/Ski-out', 'Smart_TV', 'Smart_lock', 'Smoke_detector',
       'Smoking_allowed', 'Sound_system', 'Stair_gates',
       'Step-free_shower', 'Stove', 'Suitable_for_events', 'Sun_loungers',
       'TV', 'Table_corner_guards', 'Terrace', 'Toilet_paper',
       'Walk-in_shower', 'Washer', 'Waterfront',
       'Well-lit_path_to_entrance', 'Wheelchair_accessible',
       'Wide_clearance_to_shower', 'Wide_doorway_to_guest_bathroom',
       'Wide_entrance', 'Wide_entrance_for_guests', 'Wide_entryway',
       'Wide_hallways', 'Wifi', 'Window_guards', 'Wine_cooler', '_toilet',
       'translation_missing:_en.hosting_amenity_49',
       'translation_missing:_en.hosting_amenity_50'], dtype=object)

In [51]:
amenities_one_hot_enc = pd.DataFrame(
        mlb.fit_transform(amenities_list),
        index=amenities_list.index,
        columns=mlb.classes_)

In [52]:
amenities_one_hot_enc

,,24-hour_check-in,Accessible-height_bed,Accessible-height_toilet,Air_conditioning,BBQ_grill,Baby_bath,Baby_monitor,Babysitter_recommendations,Balcony,...,Wide_entrance,Wide_entrance_for_guests,Wide_entryway,Wide_hallways,Wifi,Window_guards,Wine_cooler,_toilet,translation_missing:_en.hosting_amenity_49,translation_missing:_en.hosting_amenity_50
id,,,,,,,,,,,,,,,,,,,,,
14089799,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,1,1
2301394,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
22117621,0,0,0,0,1,1,0,0,0,0,...,0,0,0,0,1,1,0,0,0,0
22406380,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
15954965,0,0,1,0,1,0,0,0,0,0,...,0,1,0,1,1,0,0,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38624274,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
18421240,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
27546853,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
13858440,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13848383,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1

In [53]:
amenities_one_hot_enc.drop(columns='', inplace=True)
amenities_one_hot_enc

,24-hour_check-in,Accessible-height_bed,Accessible-height_toilet,Air_conditioning,BBQ_grill,Baby_bath,Baby_monitor,Babysitter_recommendations,Balcony,Bath_towel,...,Wide_entrance,Wide_entrance_for_guests,Wide_entryway,Wide_hallways,Wifi,Window_guards,Wine_cooler,_toilet,translation_missing:_en.hosting_amenity_49,translation_missing:_en.hosting_amenity_50
id,,,,,,,,,,,,,,,,,,,,,
14089799,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,1,1
2301394,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
22117621,0,0,0,1,1,0,0,0,0,0,...,0,0,0,0,1,1,0,0,0,0
22406380,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
15954965,0,1,0,1,0,0,0,0,0,0,...,0,1,0,1,1,0,0,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38624274,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
18421240,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
27546853,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
13858440,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13848383,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1

In [54]:
amenities_one_hot_enc.to_csv('amenities.csv')

In [55]:
df_listings_filtered_sampled.to_csv('anuncios.csv')

In [56]:
# Estimativa do valor do metro quadrado por bairro (Fonte: prefeitura do RJ - http://www2.rio.rj.gov.br/smf/siam/logradouro.asp)  

metro_quadrado = {
    'Ipanema':20907,
    'Copacabana':12170,
    'Leme':12210,
    'Catete':10487, 
    'Lapa':3276,
    'Barra da Tijuca':9335, 
    'Inhaúma':1483, 
    'Leblon':23626, 
    'Vila Kosmos':1540, 
    'Botafogo':11379,
    'Recreio dos Bandeirantes':6119, 
    'Tijuca':6194, 
    'Glória':9263, 
    'Laranjeiras':9688,
    'Santa Teresa':7868, 
    'Engenho de Dentro':2050, 
    'Centro':7659, 
    'Jardim Botânico':14270,
    'Joá':7972, 
    'Vidigal':1750, 
    'Flamengo':11098, 
    'Gávea':13813, 
    'Rio Comprido':1669,
    'Engenho Novo':3554, 
    'Humaitá':11683, 
    'São Cristóvão':1813, 
    'Cosme Velho':8459,
    'Vila Isabel':5086, 
    'Maracanã':2296, 
    'Andaraí':4962, 
    'Saúde':1812, 
    'Benfica':1273, 
    'Lagoa':15615,
    'Méier':2728, 
    'Marechal Hermes':1212, 
    'Penha':1735, 
    'São Conrado':12210, 
    'Urca':11662,
    'Todos os Santos':2280, 
    'Grajaú':4996, 
    'Lins de Vasconcelos':862,
    'Parque Anchieta':856, 
    'Del Castilho':1620, 
    'Estacio': 1689, 
    'Cachambi':1474,
    'Praça da Bandeira':2286, 
    'Gamboa':1665, 
    'Vaz Lobo':1185, 
    'Irajá':1203, 
    'Olaria':1814, 
    'Madureira':1572,
    'Bonsucesso':1816, 
    'Rocha':1739, 
    'Quintino Bocaiúva':1373, 
    'Vila da Penha':1986,
    'Tomás Coelho':1200, 
    'Bento Ribeiro':1498, 
    'Abolição': 1636, 
    'Brás de Pina': 1340,
    'Riachuelo':1798, 
    'Guadalupe':1170, 
    'Parada de Lucas':1063, 
    'Grumari':2600, 
    'Rocinha':1532,
    'Encantado':1640, 
    'Cordovil':1250, 
    'Barra de Guaratiba':1400, 
    'Cidade Nova':2423,
    'Maria da Graça':1737, 
    'Piedade':1548, 
    'Oswaldo Cruz':1304, 
    'Santo Cristo':1527,
    'Penha Circular': 1565, 
    'Higienópolis':1832, 
    'Catumbi':1157, 
    'Engenho da Rainha':1170,
    'Pilares':1576, 
    'Ramos':1513, 
    'Cascadura':1500, 
    'Sampaio':1699, 
    'Barros filho':743, 
    'Jacaré':1230, 
    'Rocha Miranda':1330, 
    'Caju':867, 
    'Colégio':1069, 
    'Coelho Neto':1085,
    'Mangueira':489 , 
    'Ricardo de Albuquerque':1011 , 
    'Anchieta':964 , 
    'Manguinhos':440,
    'Pavuna':2192, 
    'Vigário Geral':1026 , 
    'Vincente de Carvalho':1271,
    'Honório Gurgel':3064, 
    'Cavalcante':980, 
    'Deodoro':1000, 
    'Complexo do Alemão':543,
}

metro_quadrado_bairros = pd.DataFrame(data=list(metro_quadrado.items()),columns=['neighbourhood','m2'])
metro_quadrado_bairros = metro_quadrado_bairros.set_index('neighbourhood')
metro_quadrado_bairros

                         m2
neighbourhood
Ipanema               20907
Copacabana            12170
Leme                  12210
Catete                10487
Lapa                   3276
...                     ...
Vincente de Carvalho   1271
Honório Gurgel         3064
Cavalcante              980
Deodoro                1000
Complexo do Alemão      543

[97 rows x 1 columns]

In [57]:
metro_quadrado_bairros.to_csv('metro_quadrado.csv')